version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - '1993:1993'
    volumes:
      - ./backend:/app
    env_file:
      - ./env/backend.env
    stdin_open: true
    tty: true
    platform: linux/arm64/v8
  frontend:
    build: ./frontend
    ports:
      - '3000:3000'
    volumes:
      - ./frontend/src:/app/src
    stdin_open: true
    tty: true
    depends_on:
      - backend